name: library_client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  go_router: ^12.1.1
  sidebarx: ^0.16.3
  intl: ^0.18.0
  auto_size_text: ^3.0.0
  lottie: ^2.7.0
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.2
  searchfield: ^0.8.9
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  expansion_tile_group: ^1.2.4
  auto_height_grid_view: ^1.0.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  lint: ^2.2.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
